import type { RouteComponent } from "vue-router";

export interface DocPage {
  path: string;
  title: string;
  description: string;
  section: string;
  group?: string;
  /** Component name in src/lib, for the API tables and the "Copy import" button. */
  component?: string;
  /** Source file shown in the page header. */
  source?: string;
  badge?: string;
  /** The page renders its own hero instead of the standard header. */
  hideHeader?: boolean;
  load: () => Promise<RouteComponent | { default: RouteComponent }>;
}

export const pages: DocPage[] = [
  // Getting started
  {
    path: "/getting-started/introduction",
    title: "Introduction",
    description: "The AppsCode design system: tokens, Tailwind theme and Vue 3 components for every AppsCode console.",
    section: "Getting Started",
    hideHeader: true,
    load: () => import("./pages/getting-started/IntroductionPage.vue"),
  },
  {
    path: "/getting-started/installation",
    title: "Installation",
    description: "Add the theme and components to a Vue 3 + Tailwind CSS v4 app.",
    section: "Getting Started",
    load: () => import("./pages/getting-started/InstallationPage.vue"),
  },
  {
    path: "/getting-started/theming",
    title: "Theming",
    description: "How tokens map to Tailwind utilities, and how to re-hue the brand at runtime.",
    section: "Getting Started",
    load: () => import("./pages/getting-started/ThemingPage.vue"),
  },
  {
    path: "/getting-started/dark-mode",
    title: "Dark Mode",
    description: "Light, dark and system themes: how they work and how to add them to an app.",
    section: "Getting Started",
    load: () => import("./pages/getting-started/DarkModePage.vue"),
  },
  {
    path: "/getting-started/migration",
    title: "Migration",
    description: "Moving from the Bulma-based @appscode/design-system to this Tailwind version.",
    section: "Getting Started",
    load: () => import("./pages/getting-started/MigrationPage.vue"),
  },

  // Foundations
  {
    path: "/foundations/colors",
    title: "Colors",
    description: "Brand, status and neutral scales, semantic tokens, and when to use each.",
    section: "Foundations",
    load: () => import("./pages/foundations/ColorsPage.vue"),
  },
  {
    path: "/foundations/typography",
    title: "Typography",
    description: "Geist and Geist Mono on a 13px base: headings, size scale and weights.",
    section: "Foundations",
    load: () => import("./pages/foundations/TypographyPage.vue"),
  },
  {
    path: "/foundations/spacing",
    title: "Spacing",
    description: "A 4px spacing unit with components stepping in 4s and 8s.",
    section: "Foundations",
    load: () => import("./pages/foundations/SpacingPage.vue"),
  },
  {
    path: "/foundations/radius-shadow",
    title: "Radius & Shadow",
    description: "6px controls on 10px surfaces, pills, and a soft five-step elevation scale.",
    section: "Foundations",
    load: () => import("./pages/foundations/RadiusShadowPage.vue"),
  },
  {
    path: "/foundations/icons",
    title: "Icons",
    description: "Lucide first, Phosphor as fallback, simple-icons for brands: how to import, size and label them.",
    section: "Foundations",
    load: () => import("./pages/foundations/IconsPage.vue"),
  },

  // Components
  {
    path: "/components/button",
    title: "Button",
    description: "Triggers an action or navigates. One filled primary button per view.",
    section: "Components",
    group: "Element",
    component: "AcButton",
    load: () => import("./pages/components/ButtonPage.vue"),
  },
  {
    path: "/components/button-group",
    title: "Button Group",
    description: "Groups related buttons, and a segmented control for switching views.",
    section: "Components",
    group: "Element",
    component: "AcButtons",
    load: () => import("./pages/components/ButtonGroupPage.vue"),
  },
  {
    path: "/components/badge",
    title: "Badge",
    description: "A compact label for status, tiers and versions.",
    section: "Components",
    group: "Element",
    component: "AcBadge",
    load: () => import("./pages/components/BadgePage.vue"),
  },
  {
    path: "/components/tag",
    title: "Tag",
    description: "Labels, filters and key–value pairs such as Kubernetes labels.",
    section: "Components",
    group: "Element",
    component: "AcTag",
    load: () => import("./pages/components/TagPage.vue"),
  },
  {
    path: "/components/avatar",
    title: "Avatar",
    description: "A person or organisation, as an image or initials.",
    section: "Components",
    group: "Element",
    component: "AcAvatar",
    load: () => import("./pages/components/AvatarPage.vue"),
  },
  {
    path: "/components/alert",
    title: "Alert",
    description: "An inline message that stays on screen until the situation changes.",
    section: "Components",
    group: "Element",
    component: "AcAlert",
    load: () => import("./pages/components/AlertPage.vue"),
  },
  {
    path: "/components/banner",
    title: "Banner",
    description: "A full-width announcement at the top of a page or app.",
    section: "Components",
    group: "Element",
    component: "AcBanner",
    load: () => import("./pages/components/BannerPage.vue"),
  },
  {
    path: "/components/card",
    title: "Card",
    description: "The white, bordered surface that groups related content.",
    section: "Components",
    group: "Element",
    component: "AcCard",
    load: () => import("./pages/components/CardPage.vue"),
  },
  {
    path: "/components/divider",
    title: "Divider",
    description: "Separates groups of content, with an optional label.",
    section: "Components",
    group: "Element",
    component: "AcDivider",
    load: () => import("./pages/components/DividerPage.vue"),
  },
  {
    path: "/components/kbd",
    title: "Kbd",
    description: "Shows a keyboard key or shortcut.",
    section: "Components",
    group: "Element",
    component: "AcKbd",
    load: () => import("./pages/components/KbdPage.vue"),
  },
  {
    path: "/components/spinner",
    title: "Spinner & Preloader",
    description: "Shows that something is loading, inline or for a whole area.",
    section: "Components",
    group: "Feedback",
    component: "AcSpinner",
    load: () => import("./pages/components/SpinnerPage.vue"),
  },
  {
    path: "/components/skeleton",
    title: "Skeleton",
    description: "Grey placeholder shapes shown while content loads.",
    section: "Components",
    group: "Feedback",
    component: "AcSkeleton",
    load: () => import("./pages/components/SkeletonPage.vue"),
  },
  {
    path: "/components/progress",
    title: "Progress",
    description: "Shows how far a task or quota has got.",
    section: "Components",
    group: "Feedback",
    component: "AcProgress",
    load: () => import("./pages/components/ProgressPage.vue"),
  },
  {
    path: "/components/toast",
    title: "Toast",
    description: "Brief notifications that confirm an action, raised with useToast().",
    section: "Components",
    group: "Feedback",
    component: "AcToaster",
    load: () => import("./pages/components/ToastPage.vue"),
  },
  {
    path: "/components/empty-state",
    title: "Empty State",
    description: "What to show when a list is empty, a search has no results or a page fails.",
    section: "Components",
    group: "Feedback",
    component: "AcEmptyState",
    load: () => import("./pages/components/EmptyStatePage.vue"),
  },
  {
    path: "/components/input",
    title: "Input",
    description: "A text field with a floating label, hint and error message.",
    section: "Components",
    group: "Form",
    component: "AcInput",
    load: () => import("./pages/components/InputPage.vue"),
  },
  {
    path: "/components/textarea",
    title: "Textarea",
    description: "Multi-line text entry with a floating label and character count.",
    section: "Components",
    group: "Form",
    component: "AcTextarea",
    load: () => import("./pages/components/TextareaPage.vue"),
  },
  {
    path: "/components/select",
    title: "Select",
    description: "Pick one or more values from a list, with search, groups and async options.",
    section: "Components",
    group: "Form",
    component: "AcSelect",
    load: () => import("./pages/components/SelectPage.vue"),
  },
  {
    path: "/components/checkbox",
    title: "CheckBox",
    description: "A group of independent on/off choices.",
    section: "Components",
    group: "Form",
    component: "AcCheckBox",
    load: () => import("./pages/components/CheckBoxPage.vue"),
  },
  {
    path: "/components/check-radio",
    title: "CheckRadio",
    description: "Pick exactly one option from a small, visible set.",
    section: "Components",
    group: "Form",
    component: "AcCheckRadio",
    load: () => import("./pages/components/CheckRadioPage.vue"),
  },
  {
    path: "/components/switch",
    title: "Switch",
    description: "Toggles a single setting that takes effect immediately.",
    section: "Components",
    group: "Form",
    component: "AcSwitch",
    load: () => import("./pages/components/SwitchPage.vue"),
  },
  {
    path: "/components/search-bar",
    title: "Search Bar",
    description: "A debounced search field for filtering lists.",
    section: "Components",
    group: "Form",
    component: "AcSearchBar",
    load: () => import("./pages/components/SearchBarPage.vue"),
  },
  {
    path: "/components/file-upload",
    title: "File Upload",
    description: "Pick or drop files, with type and size checks.",
    section: "Components",
    group: "Form",
    component: "AcFileUpload",
    load: () => import("./pages/components/FileUploadPage.vue"),
  },
  {
    path: "/components/form",
    title: "Form",
    description: "Form layout with sections and a sticky Save/Cancel footer.",
    section: "Components",
    group: "Form",
    component: "AcForm",
    load: () => import("./pages/components/FormPage.vue"),
  },
  {
    path: "/components/theme-mode",
    title: "Theme Mode",
    description: "Lets people choose light, dark or system theme.",
    section: "Components",
    group: "Form",
    component: "AcThemeMode",
    load: () => import("./pages/components/ThemeModePage.vue"),
  },
  {
    path: "/components/modal",
    title: "Modal",
    description: "A focused dialog for short tasks that need an answer.",
    section: "Components",
    group: "Overlay",
    component: "AcModal",
    load: () => import("./pages/components/ModalPage.vue"),
  },
  {
    path: "/components/delete-modal",
    title: "Delete Modal",
    description: "Confirms a destructive action, optionally by typing the name.",
    section: "Components",
    group: "Overlay",
    component: "AcDeleteModal",
    load: () => import("./pages/components/DeleteModalPage.vue"),
  },
  {
    path: "/components/side-panel",
    title: "Side Panel",
    description: "A panel that slides in from the side for details and edit forms.",
    section: "Components",
    group: "Overlay",
    component: "AcSidePanel",
    load: () => import("./pages/components/SidePanelPage.vue"),
  },
  {
    path: "/components/dropdown",
    title: "Dropdown",
    description: "A menu of actions opened from a button.",
    section: "Components",
    group: "Overlay",
    component: "AcDropdown",
    load: () => import("./pages/components/DropdownPage.vue"),
  },
  {
    path: "/components/tooltip",
    title: "Tooltip",
    description: "A short hint shown on hover or focus.",
    section: "Components",
    group: "Overlay",
    component: "AcTooltip",
    load: () => import("./pages/components/TooltipPage.vue"),
  },
  {
    path: "/components/sidebar",
    title: "Sidebar",
    description: "The app's main navigation: sections, nested items and a collapsed mode.",
    section: "Components",
    group: "Layout",
    component: "AcSidebar",
    load: () => import("./pages/components/SidebarPage.vue"),
  },
  {
    path: "/components/navbar",
    title: "Navbar",
    description: "The top bar of the app: logo, navigation, search and user menu.",
    section: "Components",
    group: "Layout",
    component: "AcNavbar",
    load: () => import("./pages/components/NavbarPage.vue"),
  },
  {
    path: "/components/header",
    title: "Header",
    description: "The page title bar with back button, breadcrumb and actions.",
    section: "Components",
    group: "Layout",
    component: "AcHeader",
    load: () => import("./pages/components/HeaderPage.vue"),
  },
  {
    path: "/components/content-table",
    title: "Content Table",
    description: "A card that frames a list with title, search, filters and actions.",
    section: "Components",
    group: "Layout",
    component: "AcContentTable",
    load: () => import("./pages/components/ContentTablePage.vue"),
  },
  {
    path: "/components/section",
    title: "Section Content",
    description: "Groups part of a page under a heading, optionally collapsible.",
    section: "Components",
    group: "Layout",
    component: "AcSectionContent",
    load: () => import("./pages/components/SectionPage.vue"),
  },
  {
    path: "/components/accordion",
    title: "Accordion",
    description: "Stacked sections that expand and collapse.",
    section: "Components",
    group: "Layout",
    component: "AcAccordion",
    load: () => import("./pages/components/AccordionPage.vue"),
  },
  {
    path: "/components/tabs",
    title: "Tabs",
    description: "Switches between sibling views of the same resource.",
    section: "Components",
    group: "Navigation",
    component: "AcTabs",
    load: () => import("./pages/components/TabsPage.vue"),
  },
  {
    path: "/components/steps",
    title: "Steps",
    description: "Shows progress through a multi-step flow.",
    section: "Components",
    group: "Navigation",
    component: "AcSteps",
    load: () => import("./pages/components/StepsPage.vue"),
  },
  {
    path: "/components/pagination",
    title: "Pagination",
    description: "Moves between pages of a long list.",
    section: "Components",
    group: "Navigation",
    component: "AcPagination",
    load: () => import("./pages/components/PaginationPage.vue"),
  },
  {
    path: "/components/table",
    title: "Table",
    description: "Lists resources with sorting, loading and empty states.",
    section: "Components",
    group: "Data",
    component: "AcTable",
    load: () => import("./pages/components/TablePage.vue"),
  },
  {
    path: "/components/info-table",
    title: "Info Table",
    description: "Key–value details of one resource.",
    section: "Components",
    group: "Data",
    component: "AcInfoTable",
    load: () => import("./pages/components/InfoTablePage.vue"),
  },

  // Examples
  {
    path: "/examples/databases",
    title: "Databases page",
    description: "A full console page built only from design-system components: stats, filter tabs, table and a create wizard.",
    section: "Examples",
    badge: "Demo",
    load: () => import("./pages/examples/DatabasesPage.vue"),
  },
  {
    path: "/examples/database-detail",
    title: "Database detail",
    description: "A resource detail page: header with status and actions, tabs, info tables, usage and a danger zone.",
    section: "Examples",
    badge: "Demo",
    load: () => import("./pages/examples/DatabaseDetailPage.vue"),
  },
  {
    path: "/examples/create-database",
    title: "Create form",
    description: "A full-page create form with sections, validation and a sticky footer.",
    section: "Examples",
    badge: "Demo",
    load: () => import("./pages/examples/CreateDatabasePage.vue"),
  },
  {
    path: "/examples/settings",
    title: "Settings",
    description: "An account settings page with side navigation, forms and toggles.",
    section: "Examples",
    badge: "Demo",
    load: () => import("./pages/examples/SettingsPage.vue"),
  },
  {
    path: "/examples/states",
    title: "Empty & error states",
    description: "Empty lists, no search results, loading, errors and a 404 page.",
    section: "Examples",
    badge: "Demo",
    load: () => import("./pages/examples/StatesPage.vue"),
  },
  {
    path: "/examples/app-shell",
    title: "App shell",
    description: "The frame around every console page: sidebar, navbar and content area.",
    section: "Examples",
    badge: "Demo",
    load: () => import("./pages/examples/AppShellPage.vue"),
  },
];

for (const p of pages) if (p.component) p.source = `src/lib/components/${p.component}.vue`;

export const sections = [...new Set(pages.map((p) => p.section))];
